version: '3'
services:
  app:
    build: .
    ports:
      - '3333:3333'
      - '7331:7331'
      - '5858:5858'
      - '9229:9229'
    volumes:
      - .:/opt/app
      - reserved:/opt/app/node_modules/
    entrypoint: ['/bin/bash', './entrypoint.sh']
  postgres:
    image: postgres:10
    ports:
      - '5434:5432'
    environment:
      - DEBUG=false
      - DB_USER=postgres
      - DB_PASS=docker
      - DB_NAME=mariastore
volumes:
  reserved:
